server:
  port: 8081

spring:
  application:
    name: library-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
